# Generated by Django 5.2.8 on 2025-11-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_evento_organizador_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
