# Generated by Django 5.2.1 on 2025-12-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='confirmado',
        ),
    ]
