# Generated by Django 5.2.1 on 2025-11-19 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_evento_cupo_maximo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='confirmado',
        ),
        migrations.AlterField(
            model_name='boleto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='tickets.evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cupo_maximo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
