# Generated by Django 5.2.1 on 2025-12-11 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_transferencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transferido_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transferido_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
