# Generated by Django 5.2.1 on 2025-12-12 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_fecha_transferencia_ticket_transferido_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_transferidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
