# Generated by Django 5.2.1 on 2025-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
