# Generated by Django 5.2.1 on 2025-12-12 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_incidencia_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
